try {
    alertt('Welcome')
} catch (error) {
    console.log('error');
}